### ISSUE TITLE
Maven Central hosting for Jipsy

### ISSUE THREAD

**Issue by allquixotic** [aalmiray/jipsy#3]
Hi Andres,

Following the amazing success of having Griffon up on Maven Central, it seems like Jipsy is a transitive dependency for compiling a Griffon skeleton project... So would you be able to put Jipsy up on OSSRH as well?

This is off-topic for _this_ GitHub repo, but on another note, if there are any other dependencies you maintain that are required for the core Griffon Framework to work, and are only on Bintray, would you be able to get them up on OSSRH as well?

Thanks for your great support!

**Comment by aalmiray** [comment]
Ah yes, both Jipsy and Gipsy must be uploaded to MC too. I think those are the only two dependencies left that are specifically hosted at JCenter as of today, all of the other Griffon core dependencies are readily available at MC and JCenter.

**Comment by aalmiray** [comment]
Version `0.4.1` for Jipsy and Gipsy should be available on Maven Central in a couple of hours. All artifacts are readily available form JCenter. You will have to update your project settings to pull in this version instead of the default `0.4.0`.

Griffon 2.12.0 will upgrade to version `0.4.1`.

**Comment by shane-axiom** [comment]
@aalmiray It looks like release 0.5.1 hasn't made it to Maven Central.

https://search.maven.org/search?q=jipsy

**Comment by aalmiray** [comment]
Oh that's right, Jipsy is uploaded manually to Bintray and I forgot to sync it to MC.
Bintray now claims sync happened  at Wed Oct 17 15:07:16 GMT 2018. The artifacts should be available from MC in a couple of hours.
